/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Classes.Aluguel_Carros;
import Classes.Hospede;
import Classes.Quartos;
import Classes.classBabySitter;
import Classes.classRestaurante;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.BadLocationException;
import javax.swing.text.StyledDocument;
import plus.PDFGenerate;

/**
 *
 * @author Paulo
 */
public class Interno6 extends javax.swing.JDialog {

    ArrayList<Hospede> arrayListHospede;
    ArrayList<Quartos> arrayListQuartos;
    ArrayList<Aluguel_Carros> arrayListAluguel;
    ArrayList<classRestaurante> arrayListRestaurante;
    ArrayList<classBabySitter> arrayListBabySitter;

    /**
     * Creates new form Interno6
     */
    public Interno6(java.awt.Frame parent, boolean modal, ArrayList<Quartos> rt, ArrayList<Hospede> rt2,
            ArrayList<Aluguel_Carros> rt3, ArrayList<classRestaurante> rt4, ArrayList<classBabySitter> rt5) throws BadLocationException {
        super(parent, modal);
        initComponents();
        this.arrayListQuartos = rt;
        this.arrayListHospede = rt2;
        this.arrayListAluguel = rt3;
        this.arrayListRestaurante = rt4;
        this.arrayListBabySitter = rt5;
        PreencherComboBox();
        EscolherHospede.setSelectedIndex(-1);
        painel_de_contas.setText("");

        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        cadastrarquartos = new javax.swing.JLabel();
        abasPrestacao = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtHospede = new javax.swing.JTextField();
        EscolherHospede = new javax.swing.JComboBox<>();
        btProsseguir = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        painel_de_contas = new javax.swing.JTextPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        campoNome = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        campoCartao = new javax.swing.JTextField();
        campoSubTotal = new javax.swing.JTextField();
        nomee = new javax.swing.JLabel();
        cartaodecredito = new javax.swing.JLabel();
        cartaodecredito1 = new javax.swing.JLabel();
        cartaodecredito2 = new javax.swing.JLabel();
        cartaodecredito3 = new javax.swing.JLabel();
        campovalidade = new javax.swing.JFormattedTextField();
        campocvc = new javax.swing.JFormattedTextField();
        btFinalizar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(207, 207, 207));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        cadastrarquartos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/prestacao.png"))); // NOI18N

        abasPrestacao.setEnabled(false);

        jPanel2.setBackground(new java.awt.Color(254, 254, 254));

        txtHospede.setEditable(false);
        txtHospede.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHospede.setText("Hospede:");
        txtHospede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHospedeActionPerformed(evt);
            }
        });

        EscolherHospede.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        EscolherHospede.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                EscolherHospedeItemStateChanged(evt);
            }
        });

        btProsseguir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/prosseguir1.png"))); // NOI18N
        btProsseguir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btProsseguir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btProsseguirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btProsseguirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btProsseguirMouseExited(evt);
            }
        });

        painel_de_contas.setEditable(false);
        painel_de_contas.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        painel_de_contas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                painel_de_contasKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(painel_de_contas);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(txtHospede, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EscolherHospede, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btProsseguir))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(376, 376, 376)
                        .addComponent(jLabel1)
                        .addGap(0, 125, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHospede, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EscolherHospede, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btProsseguir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        abasPrestacao.addTab("Hospedes", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(235, 235, 235));

        jTextField2.setText("jTextField2");

        jTextField3.setText("jTextField3");

        campoSubTotal.setEditable(false);
        campoSubTotal.setBackground(new java.awt.Color(235, 235, 235));
        campoSubTotal.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        campoSubTotal.setForeground(new java.awt.Color(153, 153, 153));
        campoSubTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        campoSubTotal.setAlignmentX(0.1F);
        campoSubTotal.setBorder(null);
        campoSubTotal.setCaretColor(new java.awt.Color(102, 102, 102));

        nomee.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        nomee.setText("NOME COMPLETO:");

        cartaodecredito.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cartaodecredito.setText("CARTÃO DE CREDITO:");

        cartaodecredito1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cartaodecredito1.setText("VALIDADE:");

        cartaodecredito2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cartaodecredito2.setText("CVC:");

        cartaodecredito3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cartaodecredito3.setText("SUBTOTAL:  R$");

        try {
            campovalidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            campocvc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoNome, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                            .addComponent(campoCartao))
                        .addGap(80, 80, 80)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cartaodecredito)
                    .addComponent(nomee, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                            .addComponent(campovalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(35, 35, 35)
                            .addComponent(campocvc))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(cartaodecredito1)
                                .addGap(168, 168, 168)
                                .addComponent(cartaodecredito2)
                                .addGap(154, 154, 154))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(cartaodecredito3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nomee)
                .addGap(8, 8, 8)
                .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cartaodecredito)
                .addGap(7, 7, 7)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoCartao, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cartaodecredito1)
                    .addComponent(cartaodecredito2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campovalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campocvc, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cartaodecredito3)
                    .addComponent(campoSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {campoCartao, campoNome, campoSubTotal});

        btFinalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/finalizar1.png"))); // NOI18N
        btFinalizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btFinalizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btFinalizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btFinalizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btFinalizarMouseExited(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/cartoes.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(btFinalizar)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btFinalizar)
                .addContainerGap())
        );

        abasPrestacao.addTab("Prestar Contas", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(abasPrestacao, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadastrarquartos))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cadastrarquartos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(abasPrestacao, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtHospedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHospedeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHospedeActionPerformed

    private void btProsseguirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btProsseguirMouseClicked
        if (EscolherHospede.getSelectedIndex() != -1) {
            abasPrestacao.setSelectedIndex(1);
            exibeInformacoes();
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um Hospede!");
        }
    }//GEN-LAST:event_btProsseguirMouseClicked

    private void btProsseguirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btProsseguirMouseEntered
        btProsseguir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/prosseguir2.png")));
    }//GEN-LAST:event_btProsseguirMouseEntered

    private void btProsseguirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btProsseguirMouseExited
        btProsseguir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/prosseguir1.png")));
    }//GEN-LAST:event_btProsseguirMouseExited

    private void painel_de_contasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_painel_de_contasKeyReleased

    }//GEN-LAST:event_painel_de_contasKeyReleased

    private void EscolherHospedeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_EscolherHospedeItemStateChanged
        double valorfinalquartos = 0;
        double valorfinalalug = 0;
        double valorfinalrest = 0;
        double valorfinalbaby = 0;
        if (EscolherHospede.getSelectedIndex() != -1) {

            painel_de_contas.setText("");
            StyledDocument doc = painel_de_contas.getStyledDocument();

            try {
                String cpf = this.arrayListHospede.get(EscolherHospede.getSelectedIndex()).getCpf();
                for (int i = 0; i < this.arrayListQuartos.size(); i++) {
                    if (cpf.equals(this.arrayListQuartos.get(i).getHospede_id().getCpf())) {
                        doc.insertString(doc.getLength(), "SERVIÇO: " + this.arrayListQuartos.get(i).getNomeQuarto(), null);
                        doc.insertString(doc.getLength(), "\nVALOR DIARIA: R$ " + this.arrayListQuartos.get(i).getValorQuarto(), null);

                        Calendar dataInicio = Calendar.getInstance();
                        dataInicio.setTime(this.arrayListHospede.get(i).getData_entrada());

                        Calendar dataFinal = Calendar.getInstance();
                        dataFinal.setTime(this.arrayListHospede.get(i).getData_saida());

                        // Calcula a diferença entre hoje e da data de inicio
                        long diferenca = dataFinal.getTimeInMillis() - dataInicio.getTimeInMillis();
                        // Quantidade de milissegundos em um dia
                        int tempoDia = 1000 * 60 * 60 * 24;
                        long diasDiferenca = diferenca / tempoDia;

                        valorfinalquartos += (diasDiferenca * this.arrayListQuartos.get(i).getValorQuarto());
                        doc.insertString(doc.getLength(), "\nVALOR DO SERVIÇO: R$ " + valorfinalquartos, null);
                        doc.insertString(doc.getLength(), "\n\n", null);
                    }
                }
            } catch (BadLocationException ex) {
                Logger.getLogger(Interno6.class.getName()).log(Level.SEVERE, null, ex);
            }

            try {
                String cpf = this.arrayListHospede.get(EscolherHospede.getSelectedIndex()).getCpf();
                for (int i = 0; i < this.arrayListAluguel.size(); i++) {
                    if (cpf.equals(this.arrayListAluguel.get(i).getHospede_id().getCpf())) {
                        doc.insertString(doc.getLength(), "SERVIÇO: " + this.arrayListAluguel.get(i).getTipo(), null);
                        doc.insertString(doc.getLength(), "\nDIARIAS: " + this.arrayListAluguel.get(i).getQtddiarias(), null);
                        doc.insertString(doc.getLength(), "\nSEGURO: " + this.arrayListAluguel.get(i).getSeguro(), null);
                        doc.insertString(doc.getLength(), "\nTANQUE CHEIO: " + this.arrayListAluguel.get(i).getTanque(), null);
                        valorfinalalug += (this.arrayListAluguel.get(i).getQtddiarias() * this.arrayListAluguel.get(i).getValorDiariasAluguel())
                                + this.arrayListAluguel.get(i).getSeguro() + this.arrayListAluguel.get(i).getTanque();
                        doc.insertString(doc.getLength(), "\nVALOR DO SERVIÇO: R$ " + valorfinalalug, null);
                        doc.insertString(doc.getLength(), "\n\n", null);
                    }
                }
            } catch (BadLocationException ex) {
                Logger.getLogger(Interno6.class.getName()).log(Level.SEVERE, null, ex);
            }

            try {
                String cpf = this.arrayListHospede.get(EscolherHospede.getSelectedIndex()).getCpf();
                for (int i = 0; i < this.arrayListRestaurante.size(); i++) {
                    if (cpf.equals(this.arrayListRestaurante.get(i).getHospede_id().getCpf())) {
                        doc.insertString(doc.getLength(), "SERVIÇO: " + this.arrayListRestaurante.get(i).getTipoEscolhido(), null);
                        doc.insertString(doc.getLength(), "\nPORÇÕES: " + this.arrayListRestaurante.get(i).getPorcoes_unidades(), null);
                        valorfinalrest += this.arrayListRestaurante.get(i).getPorcoes_unidades() * this.arrayListRestaurante.get(i).getValorRestaurante();
                        doc.insertString(doc.getLength(), "\nVALOR DO SERVIÇO: R$ " + valorfinalrest, null);
                        doc.insertString(doc.getLength(), "\n\n", null);
                    }
                }
            } catch (BadLocationException ex) {
                Logger.getLogger(Interno6.class.getName()).log(Level.SEVERE, null, ex);
            }

            try {
                String cpf = this.arrayListHospede.get(EscolherHospede.getSelectedIndex()).getCpf();
                for (int i = 0; i < this.arrayListBabySitter.size(); i++) {
                    if (cpf.equals(this.arrayListBabySitter.get(i).getHospede_id().getCpf())) {
                        doc.insertString(doc.getLength(), "SERVIÇO: " + this.arrayListBabySitter.get(i).getTipo(), null);
                        doc.insertString(doc.getLength(), "\nHORAS: " + this.arrayListBabySitter.get(i).getHoras(), null);
                        valorfinalbaby += this.arrayListBabySitter.get(i).getHoras() * this.arrayListBabySitter.get(i).getValorBaySitter();
                        doc.insertString(doc.getLength(), "\nVALOR DO SERVIÇO: R$ " + valorfinalbaby, null);
                        doc.insertString(doc.getLength(), "\n\n", null);
                    }
                }
            } catch (BadLocationException ex) {
                Logger.getLogger(Interno6.class.getName()).log(Level.SEVERE, null, ex);
            }

            double valorFinalTUDO = valorfinalquartos + valorfinalalug + valorfinalrest + valorfinalbaby;
            double temporad=0;
            try {
                for (int i = 0; i < this.arrayListHospede.size(); i++) {
                    temporad = this.arrayListHospede.get(i).getTemporada();
                    this.arrayListHospede.get(i).setValortotal(valorFinalTUDO);
                }
                doc.insertString(doc.getLength(), "\nAlta Temporada: R$ " + temporad, null);
                if (temporad != 0 || temporad != 0.0) {
                        valorFinalTUDO = valorFinalTUDO * temporad;
                        doc.insertString(doc.getLength(), "\n\nVALOR A PAGAR: R$ " + valorFinalTUDO, null);
                    } else {
                        doc.insertString(doc.getLength(), "\n\nVALOR A PAGAR: R$ " + valorFinalTUDO, null);
                    }
                for (int i = 0; i < this.arrayListHospede.size(); i++) {
                   
                    this.arrayListHospede.get(i).setValortotal(valorFinalTUDO);
                }
                /*doc.insertString(doc.getLength(), "\n\nVALOR A PAGAR: R$ " + valorFinalTUDO, null);
                for (int i = 0; i < this.arrayListHospede.size(); i++) {
                    this.arrayListHospede.get(i).setValortotal(valorFinalTUDO);
                    double temporad = this.arrayListHospede.get(i).getTemporada();
                    doc.insertString(doc.getLength(), "\nAlta Temporada: R$ " + temporad, null);
                    if (temporad != 0 || temporad != 0.0) {
                        valorFinalTUDO = valorFinalTUDO * temporad;
                        doc.insertString(doc.getLength(), "\n\nVALOR A PAGAR: R$ " + valorFinalTUDO, null);
                    } else {
                        doc.insertString(doc.getLength(), "\n\nVALOR A PAGAR: R$ " + valorFinalTUDO, null);
                    }
                }*/
            } catch (BadLocationException ex) {
                Logger.getLogger(Interno6.class.getName()).log(Level.SEVERE, null, ex);
            }
        }


    }//GEN-LAST:event_EscolherHospedeItemStateChanged

    private void btFinalizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btFinalizarMouseClicked
        //Object[] dados = pegaCampos();

        if ((campoNome.getText().trim().isEmpty())
                || (campoCartao.getText().trim().isEmpty())
                || (campovalidade.getText().trim().isEmpty())
                || (campocvc.getText().trim().isEmpty())) {
            JOptionPane.showMessageDialog(null, "Preencha os Campos!");
        } else {

            String cpf = this.arrayListHospede.get(EscolherHospede.getSelectedIndex()).getCpf();

            for (int i = 0; i < this.arrayListHospede.size(); i++) {
                if (cpf.equals(this.arrayListHospede.get(i).getCpf())) {
                    this.arrayListHospede.remove(i);
                }
            }

            for (int i = 0; i < this.arrayListQuartos.size(); i++) {
                if (cpf.equals(this.arrayListQuartos.get(i).getHospede_id().getCpf())) {
                    this.arrayListQuartos.remove(i);
                    Quartos.adicionarVaga(i);
                }
            }

            for (int i = 0; i < this.arrayListAluguel.size(); i++) {
                if (cpf.equals(this.arrayListAluguel.get(i).getHospede_id().getCpf())) {
                    this.arrayListAluguel.remove(i);

                }
            }

            for (int i = 0; i < this.arrayListRestaurante.size(); i++) {
                if (cpf.equals(this.arrayListRestaurante.get(i).getHospede_id().getCpf())) {
                    this.arrayListRestaurante.remove(i);

                }
            }
            for (int i = 0; i < this.arrayListBabySitter.size(); i++) {
                if (cpf.equals(this.arrayListBabySitter.get(i).getHospede_id().getCpf())) {
                    this.arrayListBabySitter.remove(i);

                }
            }
            limparCampos();
            JOptionPane.showMessageDialog(null, "Contrato Finalizado");
        }
    }//GEN-LAST:event_btFinalizarMouseClicked

    private void btFinalizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btFinalizarMouseEntered
        btFinalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/finalizar2.png")));
    }//GEN-LAST:event_btFinalizarMouseEntered

    private void btFinalizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btFinalizarMouseExited
        btFinalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/finalizar1.png")));
    }//GEN-LAST:event_btFinalizarMouseExited

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> EscolherHospede;
    private javax.swing.JTabbedPane abasPrestacao;
    private javax.swing.JLabel btFinalizar;
    private javax.swing.JLabel btProsseguir;
    private javax.swing.JLabel cadastrarquartos;
    private javax.swing.JTextField campoCartao;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoSubTotal;
    private javax.swing.JFormattedTextField campocvc;
    private javax.swing.JFormattedTextField campovalidade;
    private javax.swing.JLabel cartaodecredito;
    private javax.swing.JLabel cartaodecredito1;
    private javax.swing.JLabel cartaodecredito2;
    private javax.swing.JLabel cartaodecredito3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel nomee;
    private javax.swing.JTextPane painel_de_contas;
    private javax.swing.JTextField txtHospede;
    // End of variables declaration//GEN-END:variables

    private void limparCampos() {
        this.campoNome.setText("");
        this.campoCartao.setText("");
        this.campoSubTotal.setText("");
        this.campovalidade.setText("");
        this.campocvc.setText("");

    }

    private void PreencherComboBox() {
        EscolherHospede.removeAllItems();
        for (int i = 0; i < arrayListHospede.size(); i++) {
            EscolherHospede.addItem(i + ". " + arrayListHospede.get(i).getNome());
        }
        //EscolherHospede.setSelectedIndex(-1);
    }

    public void exibeInformacoes() {
        String cpf = this.arrayListHospede.get(EscolherHospede.getSelectedIndex()).getCpf();
        for (int i = 0; i < this.arrayListHospede.size(); i++) {
            if (cpf.equals(arrayListHospede.get(i).getCpf())) {
                campoNome.setText(String.valueOf(arrayListHospede.get(i).getNome()));
                campoCartao.setText(String.valueOf(arrayListHospede.get(i).getCartao_credito()));
                campoSubTotal.setText(String.valueOf(arrayListHospede.get(i).getValortotal()));
            }
        }
    }

}
