/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Classes.Hospede;
import Classes.Quartos;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Paulo
 */
public class Interno1 extends javax.swing.JDialog {

    ArrayList<Hospede> arrayListHospede;
  
    private int posicao;

    /**
     * Creates new form Interno1
     *
     * @param parent
     * @param modal
     * @param rt
     */
    public Interno1(java.awt.Frame parent, boolean modal, ArrayList<Hospede> rt) {
        super(parent, modal);
        initComponents();
        this.arrayListHospede = rt;
        carregarTable();

        this.setLocationRelativeTo(null);

        botaoDelete.setVisible(false);
        botaoAtualizar.setVisible(false);
        botaoNovo.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        cadastrarhospede = new javax.swing.JLabel();
        abasHospede = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        tfNome = new javax.swing.JTextField();
        tfCpf = new javax.swing.JTextField();
        tfTel = new javax.swing.JTextField();
        cartao = new javax.swing.JLabel();
        NOME = new javax.swing.JLabel();
        entrada = new javax.swing.JLabel();
        cpf = new javax.swing.JLabel();
        saida = new javax.swing.JLabel();
        cel = new javax.swing.JLabel();
        botaoCadastrar = new javax.swing.JLabel();
        botaoAtualizar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        botaoNovo = new javax.swing.JLabel();
        tfDataInicial = new javax.swing.JFormattedTextField();
        tfDataFinal = new javax.swing.JFormattedTextField();
        btEstacao = new javax.swing.JRadioButton();
        tfCartao = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableHospede = new javax.swing.JTable();
        tfPesquisar = new javax.swing.JTextField();
        botaoDelete = new javax.swing.JButton();
        botaoEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(207, 207, 207));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        cadastrarhospede.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/cadastrarhospede.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(254, 254, 254));

        tfNome.setText("João Paulo");

        tfCpf.setText("1345678910");

        tfTel.setText("558388080808");

        cartao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/cartao.png"))); // NOI18N

        NOME.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/NOME.png"))); // NOI18N

        entrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/entrada.png"))); // NOI18N

        cpf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/cpf.png"))); // NOI18N

        saida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/saida.png"))); // NOI18N

        cel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/CEL.png"))); // NOI18N

        botaoCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/btn_entered.png"))); // NOI18N
        botaoCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoCadastrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoCadastrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoCadastrarMouseExited(evt);
            }
        });

        botaoAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/atualizar1.png"))); // NOI18N
        botaoAtualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoAtualizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoAtualizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoAtualizarMouseExited(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/man.png"))); // NOI18N

        botaoNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/novo1.png"))); // NOI18N
        botaoNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoNovoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoNovoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoNovoMouseExited(evt);
            }
        });

        try {
            tfDataInicial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####/##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfDataInicial.setText("2018/08/10");

        try {
            tfDataFinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####/##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfDataFinal.setText("2018/08/12");

        btEstacao.setBackground(new java.awt.Color(255, 255, 255));
        btEstacao.setText("Alta Estação");

        try {
            tfCartao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfCartao.setText("00020202020");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(NOME)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(saida)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfDataFinal))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(entrada)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfDataInicial))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cartao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCartao))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfTel))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cpf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCpf)))
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(botaoCadastrar)
                        .addComponent(botaoAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botaoNovo))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(btEstacao)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tfCpf, tfNome, tfTel});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NOME, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cpf))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cartao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfCartao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfDataInicial)
                            .addComponent(entrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(saida, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfDataFinal)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoAtualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoNovo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 5, Short.MAX_VALUE)
                .addComponent(btEstacao)
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {tfCpf, tfNome, tfTel});

        abasHospede.addTab("Cadastrar Hospede", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        TableHospede.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableHospede.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableHospedeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableHospede);

        tfPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPesquisarActionPerformed(evt);
            }
        });
        tfPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfPesquisarKeyReleased(evt);
            }
        });

        botaoDelete.setText("Deletar");
        botaoDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDeleteActionPerformed(evt);
            }
        });

        botaoEditar.setText("Editar");
        botaoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(botaoEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoDelete)
                    .addComponent(botaoEditar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        abasHospede.addTab("Pesquisar Hospede", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 11, Short.MAX_VALUE)
                        .addComponent(abasHospede, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(cadastrarhospede)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cadastrarhospede)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(abasHospede, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPesquisarKeyReleased
        String pesquisa = tfPesquisar.getText().trim();

        if (pesquisa.equals("")) {
            carregarTable();
        } else {
            DefaultTableModel modelo = new DefaultTableModel(new Object[]{"ID", "Nome", "CPF", "Telefone", "Data F."}, 0) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };

            for (int i = 0; i < this.arrayListHospede.size(); i++) {
                if (this.arrayListHospede.get(i).getNome().equals(pesquisa)) {
                    modelo.addRow(new Object[]{
                        i,
                        this.arrayListHospede.get(i).getNome(),
                        this.arrayListHospede.get(i).getCpf(),
                        this.arrayListHospede.get(i).getTelefone(),
                        this.arrayListHospede.get(i).getData_saida(),});
                }
            }

            TableHospede.setModel(modelo);
        }


    }//GEN-LAST:event_tfPesquisarKeyReleased

    private void botaoDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDeleteActionPerformed
        int linha = TableHospede.getSelectedRow();
        if (linha >= 0 && linha < this.arrayListHospede.size()) {
            int id = Integer.valueOf(pegarIDLinha(linha));
            this.arrayListHospede.remove(id);
            carregarTable();
        }
    }//GEN-LAST:event_botaoDeleteActionPerformed

    private void TableHospedeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableHospedeMouseClicked
        int linha = TableHospede.getSelectedRow();

        if (linha >= 0 && linha < this.arrayListHospede.size()) {
//            System.out.println(TableHospede.getValueAt(linha, 0).toString());

        }
    }//GEN-LAST:event_TableHospedeMouseClicked

    private void botaoAtualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoAtualizarMouseClicked
        System.out.println(this.posicao);
        Hospede h = this.arrayListHospede.get(this.posicao);
        h = this.updateClass(h);
        this.arrayListHospede.set(this.posicao, h);
        JOptionPane.showMessageDialog(null, "Hospede Atualizado", "OK!", JOptionPane.INFORMATION_MESSAGE);
        carregarTable();
    }//GEN-LAST:event_botaoAtualizarMouseClicked

    private void botaoCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoCadastrarMouseClicked
        if (this.validacao()) {
            this.arrayListHospede.add(instanceClass());
            limparCampos();
            carregarTable();

            for (int i = 0; i < this.arrayListHospede.size(); i++) {
               // System.out.println(this.arrayListHospede.get(i).getNome());
            }
        }
    }//GEN-LAST:event_botaoCadastrarMouseClicked

    private void botaoCadastrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoCadastrarMouseExited
        botaoCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/btn_entered.png")));
    }//GEN-LAST:event_botaoCadastrarMouseExited

    private void botaoCadastrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoCadastrarMouseEntered
        botaoCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/btn_exited.png")));
    }//GEN-LAST:event_botaoCadastrarMouseEntered

    private void botaoNovoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoNovoMouseClicked
        limparCampos();
        botaoAtualizar.setVisible(false);
        botaoCadastrar.setVisible(true);
        carregarTable();
    }//GEN-LAST:event_botaoNovoMouseClicked

    private void botaoAtualizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoAtualizarMouseEntered
        botaoAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/atualizar2.png")));
    }//GEN-LAST:event_botaoAtualizarMouseEntered

    private void botaoAtualizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoAtualizarMouseExited
        botaoAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/atualizar1.png")));
    }//GEN-LAST:event_botaoAtualizarMouseExited

    private void botaoNovoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoNovoMouseEntered
        botaoNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/novo2.png")));
    }//GEN-LAST:event_botaoNovoMouseEntered

    private void botaoNovoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoNovoMouseExited
        botaoNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/novo1.png")));
    }//GEN-LAST:event_botaoNovoMouseExited

    private void botaoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditarActionPerformed
       int linha = TableHospede.getSelectedRow();
        if (linha >= 0 && linha < this.arrayListHospede.size()) {
            botaoNovo.setVisible(true);
            botaoAtualizar.setVisible(true);
            botaoCadastrar.setVisible(false);
            abasHospede.setSelectedIndex(0);
            limparCampos();
            carregarCampos(linha);

        }
    }//GEN-LAST:event_botaoEditarActionPerformed

    private void tfPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPesquisarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NOME;
    private javax.swing.JTable TableHospede;
    private javax.swing.JTabbedPane abasHospede;
    private javax.swing.JLabel botaoAtualizar;
    private javax.swing.JLabel botaoCadastrar;
    private javax.swing.JButton botaoDelete;
    private javax.swing.JButton botaoEditar;
    private javax.swing.JLabel botaoNovo;
    private javax.swing.JRadioButton btEstacao;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel cadastrarhospede;
    private javax.swing.JLabel cartao;
    private javax.swing.JLabel cel;
    private javax.swing.JLabel cpf;
    private javax.swing.JLabel entrada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel saida;
    private javax.swing.JFormattedTextField tfCartao;
    private javax.swing.JTextField tfCpf;
    private javax.swing.JFormattedTextField tfDataFinal;
    private javax.swing.JFormattedTextField tfDataInicial;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfPesquisar;
    private javax.swing.JTextField tfTel;
    // End of variables declaration//GEN-END:variables

    private void limparCampos() {
        this.tfNome.setText("");
        this.tfCpf.setText("");
        this.tfTel.setText("");
        this.tfCartao.setText("");
        this.tfDataInicial.setText("");
        this.tfDataFinal.setText("");
    }
    
    public double getAltaTemporada() {
        return (btEstacao.isSelected()) ? Double.valueOf(String.valueOf(Hospede.listahospede[0][1])) : 0.0;
    }
    
    
    private int pegarIDLinha(int linha) {
        return Integer.valueOf(TableHospede.getValueAt(linha, 0).toString());
    }

    private void carregarCampos(int linha) {
        this.posicao = Integer.valueOf(pegarIDLinha(linha));

        this.tfNome.setText(this.arrayListHospede.get(posicao).getNome());
        this.tfCpf.setText(this.arrayListHospede.get(posicao).getCpf());
        this.tfTel.setText(this.arrayListHospede.get(posicao).getTelefone());
        this.tfCartao.setText(String.valueOf(this.arrayListHospede.get(posicao).getCartao_credito()));
        this.tfDataInicial.setText(this.getDate(this.arrayListHospede.get(posicao).getData_entrada()));
        this.tfDataFinal.setText(this.getDate(this.arrayListHospede.get(posicao).getData_saida()));
    }

    private Hospede instanceClass() {
        //Hospede(String nome, String cpf, String telefone, int cartao_credito, Date data_entrada, Date data_saida)
        Object[] dados = pegaCampos();
        Hospede h = new Hospede(
                String.valueOf(dados[0]),
                String.valueOf(dados[1]),
                String.valueOf(dados[2]),
                String.valueOf(dados[3]),
                stringToDate(String.valueOf(dados[4]), "yyyy/MM/dd"),
                stringToDate(String.valueOf(dados[5]), "yyyy/MM/dd"),
                getAltaTemporada()
        );
         /*for (int i = 0; i < this.arrayListHospede.size(); i++) {
             //pra ver se funcionava
               System.out.println(this.arrayListHospede.get(i).getData_entrada());
               System.out.println(this.arrayListHospede.get(i).getData_saida());
         }*/
        return h;
        
        
        
    }

    private Hospede updateClass(Hospede h) {
        //Hospede(String nome, String cpf, String telefone, int cartao_credito, Date data_entrada, Date data_saida)
        Object[] dados = pegaCampos();
        h.setNome(String.valueOf(dados[0]));
        h.setCpf(String.valueOf(dados[1]));
        h.setTelefone(String.valueOf(dados[2]));
        h.setCartao_credito(String.valueOf(dados[3]));
        h.setData_entrada(stringToDate(String.valueOf(dados[4]), "yyyy/MM/dd"));
        h.setData_saida(stringToDate(String.valueOf(dados[5]), "yyyy/MM/dd"));
        return h;
    }

    private Object[] pegaCampos() {
        Object[] campos = {
            this.tfNome.getText().trim().toUpperCase(),
            this.tfCpf.getText().trim(),
            this.tfTel.getText().trim(),
            this.tfCartao.getText().trim(),
            this.tfDataInicial.getText(),
            this.tfDataFinal.getText()
        };
        return campos;
    }

    public static Date stringToDate(String str, String format) {
        try {
            return new SimpleDateFormat(format).parse(str);
        } catch (ParseException ex) {
            try {
                throw new Exception("Erro na função StringToDate: ", ex);
            } catch (Exception ex1) {
                System.out.println("Erro na função StringToDate: " + ex1);
            }
        }
        return null;
    }

    public static String getDate(Date date) {
        return DateFormat.getDateInstance().format(date);
    }

    private boolean validacao() {

        // VALIDAR NOME
        if (tfNome.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Coloque seu nome", "Erro!", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (tfNome.getText().trim().length() < 6) {
            JOptionPane.showMessageDialog(null, "Insira no minimo 6 caracteres", "Erro!", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (this.hasCpf(tfCpf.getText().trim())) {
            return false;
        }
        if (tfCpf.getText().trim().length() < 5) {
            JOptionPane.showMessageDialog(null, "Insira no minimo 5 caracteres", "Erro!", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (tfCpf.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Coloque seu cpf", "Erro!", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (tfTel.getText().trim().length() < 11) {
            JOptionPane.showMessageDialog(null, "Insira no minimo 11 caracteres", "Erro!", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (tfTel.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Coloque seu numero", "Erro!", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (tfCartao.getText().trim().length() < 11) {
            JOptionPane.showMessageDialog(null, "Insira no minimo 11 caracteres", "Erro!", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (tfCartao.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Coloque seu cartao", "Erro!", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        return true;
    }

    private boolean hasCpf(String cpf) {
        for (int i = 0; i < this.arrayListHospede.size(); i++) {
            if (this.arrayListHospede.get(i).getCpf().equals(cpf)) {
                JOptionPane.showMessageDialog(null, "CPF ja cadaastrado", "Erro!", JOptionPane.ERROR_MESSAGE);
                return true;
            }
        }
        return false;
    }

    private void carregarTable() {

        DefaultTableModel modelo = new DefaultTableModel(new Object[]{"ID", "Nome", "CPF", "Telefone", "Data F."}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        for (int i = 0; i < this.arrayListHospede.size(); i++) {

            modelo.addRow(new Object[]{
                i,
                this.arrayListHospede.get(i).getNome(),
                this.arrayListHospede.get(i).getCpf(),
                this.arrayListHospede.get(i).getTelefone(),
                this.arrayListHospede.get(i).getData_saida(),});
        }

        TableHospede.setModel(modelo);

    }

    /*private void criaRegistro() {

        //Hospede(String nome, String cpf, String telefone, int cartao_credito, Date data_entrada, Date data_saida)
        for (int i = 0; i < 30; i++) {
            Hospede h = new Hospede(
                    "Nome" + i,
                    "CPF" + i,
                    "Telefone" + i,
                    123456,
                    stringToDate("2018/07/06", "yyyy/MM/dd"),
                    stringToDate("2018/07/09", "yyyy/MM/dd")
            );
            this.arrayListHospede.add(h);
        }

    }*/

}
