/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Classes.classRestaurante;
import Classes.Hospede;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Paulo
 */
public class Interno4 extends javax.swing.JDialog {

    String tipoRestaurante;
    double valorRestaurante;
    ArrayList<classRestaurante> arrayListRestaurante;
    ArrayList<Hospede> arrayListHospede;

    /**
     * Creates new form Interno4
     */
    public Interno4(java.awt.Frame parent, boolean modal, ArrayList<classRestaurante> rt, ArrayList<Hospede> rt2) {
        super(parent, modal);
        initComponents();
        this.arrayListRestaurante = rt;
        this.arrayListHospede = rt2;
        PreencherComboBox();
        carregarTableRestaurante("");

        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        Restaurante = new javax.swing.JLabel();
        abasRestaurante = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        txtHospedee = new javax.swing.JTextField();
        ImgTabela = new javax.swing.JLabel();
        btTapioca = new javax.swing.JRadioButton();
        btPamonha = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        tabelaCarros = new javax.swing.JLabel();
        EscolherHospede = new javax.swing.JComboBox<>();
        btBolo = new javax.swing.JRadioButton();
        btCanjica = new javax.swing.JRadioButton();
        btSelfService = new javax.swing.JRadioButton();
        btAgua = new javax.swing.JRadioButton();
        btCachacaN = new javax.swing.JRadioButton();
        btCachacaM = new javax.swing.JRadioButton();
        btJuizo = new javax.swing.JRadioButton();
        btSerraLimpa = new javax.swing.JRadioButton();
        btProsseguir = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfOpcao = new javax.swing.JTextField();
        tfPorcoes = new javax.swing.JTextField();
        btFinalizar = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        tfHospede = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableRestaurante = new javax.swing.JTable();
        botaoDelete = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tfPesquisar = new javax.swing.JTextField();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(207, 207, 207));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        Restaurante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/Restaurante.png"))); // NOI18N

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        txtHospedee.setEditable(false);
        txtHospedee.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHospedee.setText("Hospede:");
        txtHospedee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHospedeeActionPerformed(evt);
            }
        });

        btTapioca.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup.add(btTapioca);
        btTapioca.setText("Escolher");

        btPamonha.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup.add(btPamonha);
        btPamonha.setText("Escolher");

        tabelaCarros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/tabelarestaurante.png"))); // NOI18N

        EscolherHospede.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btBolo.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup.add(btBolo);
        btBolo.setText("Escolher");

        btCanjica.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup.add(btCanjica);
        btCanjica.setText("Escolher");

        btSelfService.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup.add(btSelfService);
        btSelfService.setText("Escolher");

        btAgua.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup.add(btAgua);
        btAgua.setText("Escolher");

        btCachacaN.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup.add(btCachacaN);
        btCachacaN.setText("Escolher");

        btCachacaM.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup.add(btCachacaM);
        btCachacaM.setText("Escolher");

        btJuizo.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup.add(btJuizo);
        btJuizo.setText("Escolher");

        btSerraLimpa.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup.add(btSerraLimpa);
        btSerraLimpa.setText("Escolher");

        btProsseguir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/prosseguir1.png"))); // NOI18N
        btProsseguir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btProsseguir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btProsseguirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btProsseguirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btProsseguirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(tabelaCarros)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btTapioca)
                                            .addComponent(btCanjica))
                                        .addGap(597, 597, 597)
                                        .addComponent(ImgTabela))
                                    .addComponent(btBolo)
                                    .addComponent(btPamonha)
                                    .addComponent(btSelfService)
                                    .addComponent(btAgua)
                                    .addComponent(btCachacaN)
                                    .addComponent(btCachacaM)
                                    .addComponent(btJuizo)
                                    .addComponent(btSerraLimpa)))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btProsseguir)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(txtHospedee, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(EscolherHospede, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHospedee, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EscolherHospede, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tabelaCarros))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(79, 79, 79)
                                        .addComponent(btTapioca)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btBolo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(125, 125, 125)
                                        .addComponent(ImgTabela)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btCanjica)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btPamonha)
                                        .addGap(18, 18, 18)
                                        .addComponent(btSelfService, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btAgua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btCachacaN, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btCachacaM)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btJuizo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btSerraLimpa)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addComponent(jLabel5))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btProsseguir)))
                .addGap(8, 8, 8))
        );

        abasRestaurante.addTab("Serviços", jPanel3);

        jPanel2.setBackground(new java.awt.Color(254, 254, 254));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/opcao.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/porcoes.png"))); // NOI18N

        tfOpcao.setEditable(false);

        btFinalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/finalizar1.png"))); // NOI18N
        btFinalizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btFinalizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btFinalizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btFinalizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btFinalizarMouseExited(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("HOSPEDE:");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        tfHospede.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btFinalizar)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfOpcao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                            .addComponent(tfHospede, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfPorcoes))))
                .addGap(371, 371, 371)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfHospede, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfOpcao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPorcoes, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(263, 263, 263)
                .addComponent(btFinalizar)
                .addGap(19, 19, 19))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(jLabel1)
                .addGap(285, 285, 285))
        );

        abasRestaurante.addTab("Dados", jPanel2);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        TableRestaurante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TableRestaurante);

        botaoDelete.setText("Deletar");
        botaoDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDeleteActionPerformed(evt);
            }
        });

        jLabel6.setText("PESQUISE O HOSPEDE PELO NOME:");

        tfPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPesquisarActionPerformed(evt);
            }
        });
        tfPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfPesquisarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(botaoDelete)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfPesquisar))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoDelete)
                    .addComponent(jLabel6)
                    .addComponent(tfPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        abasRestaurante.addTab("Pesquisar Serviço", jPanel5);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(abasRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, 522, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(Restaurante, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Restaurante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(abasRestaurante)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(282, 282, 282))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 565, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtHospedeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHospedeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHospedeeActionPerformed

    private void btFinalizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btFinalizarMouseClicked
        if (!tfPorcoes.getText().equals("")) {
            //Object[] inforest = restauranteSelecionado();
            this.arrayListRestaurante.add(instanceClass());
            JOptionPane.showMessageDialog(null, "Serviço adicionado no contrato");
            //System.out.println(instanceClass().getNomeQuarto());

        } else {
            JOptionPane.showConfirmDialog(null, "Digite o numero de porçoes");
        }
    }//GEN-LAST:event_btFinalizarMouseClicked

    private void btFinalizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btFinalizarMouseEntered
        btFinalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/finalizar2.png")));
    }//GEN-LAST:event_btFinalizarMouseEntered

    private void btFinalizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btFinalizarMouseExited
        btFinalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/finalizar1.png")));
    }//GEN-LAST:event_btFinalizarMouseExited

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btProsseguirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btProsseguirMouseClicked
        if (isSelectedRoom()) {
            // QualMarcado();
            abasRestaurante.setSelectedIndex(1);
            exibeInformacoesCompra();
        }

    }//GEN-LAST:event_btProsseguirMouseClicked

    private void btProsseguirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btProsseguirMouseEntered
        btProsseguir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/prosseguir2.png")));
    }//GEN-LAST:event_btProsseguirMouseEntered

    private void btProsseguirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btProsseguirMouseExited
        btProsseguir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/prosseguir1.png")));
    }//GEN-LAST:event_btProsseguirMouseExited

    private void tfPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPesquisarKeyReleased
        String pesquisa = tfPesquisar.getText().trim();

        if (pesquisa.equals("")) {
            carregarTableRestaurante("");
        } else {
            carregarTableRestaurante(pesquisa);
        }
    }//GEN-LAST:event_tfPesquisarKeyReleased

    private void tfPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPesquisarActionPerformed

    private void botaoDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDeleteActionPerformed
        Object[] inforest = restauranteSelecionado();
        String cpf = this.arrayListHospede.get(EscolherHospede.getSelectedIndex()).getCpf();

        for (int i = 0; i < this.arrayListRestaurante.size(); i++) {
            if (cpf.equals(this.arrayListRestaurante.get(i).getHospede_id().getCpf())) {

                this.arrayListRestaurante.remove(i);
                //System.out.println(Integer.valueOf(String.valueOf(infoquarto[2])));

                carregarTableRestaurante("");

            }
        }
    }//GEN-LAST:event_botaoDeleteActionPerformed

    private int pegarIDLinha(int linha) {
        return Integer.valueOf(TableRestaurante.getValueAt(linha, 0).toString());
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> EscolherHospede;
    private javax.swing.JLabel ImgTabela;
    private javax.swing.JLabel Restaurante;
    private javax.swing.JTable TableRestaurante;
    private javax.swing.JTabbedPane abasRestaurante;
    private javax.swing.JButton botaoDelete;
    private javax.swing.JRadioButton btAgua;
    private javax.swing.JRadioButton btBolo;
    private javax.swing.JRadioButton btCachacaM;
    private javax.swing.JRadioButton btCachacaN;
    private javax.swing.JRadioButton btCanjica;
    private javax.swing.JLabel btFinalizar;
    private javax.swing.JRadioButton btJuizo;
    private javax.swing.JRadioButton btPamonha;
    private javax.swing.JLabel btProsseguir;
    private javax.swing.JRadioButton btSelfService;
    private javax.swing.JRadioButton btSerraLimpa;
    private javax.swing.JRadioButton btTapioca;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel tabelaCarros;
    private javax.swing.JTextField tfHospede;
    private javax.swing.JTextField tfOpcao;
    private javax.swing.JTextField tfPesquisar;
    private javax.swing.JTextField tfPorcoes;
    private javax.swing.JTextField txtHospedee;
    // End of variables declaration//GEN-END:variables

    private void PreencherComboBox() {
        EscolherHospede.removeAllItems();
        for (int i = 0; i < arrayListHospede.size(); i++) {
            EscolherHospede.addItem(i + ". " + arrayListHospede.get(i).getNome());
        }
        //EscolherHospede.setSelectedIndex(-1);
    }

    /* private void QualMarcado() {
        if (btTapioca.isSelected()) {
            valorRestaurante = 10;
            tipoRestaurante = "Tapioca";
        } else if (btBolo.isSelected()) {
            valorRestaurante = 10;
            tipoRestaurante = "Bolo de Milho";
        } else if (btCanjica.isSelected()) {
            valorRestaurante = 15;
            tipoRestaurante = "Canjica";
        } else if (btBolo.isSelected()) {
            valorRestaurante = 18;
            tipoRestaurante = "Pamonha";
        } else if (btSelfService.isSelected()) {
            valorRestaurante = 30;
            tipoRestaurante = "Self Service";
        } else if (btAgua.isSelected()) {
            valorRestaurante = 2;
            tipoRestaurante = "Agua";
        } else if (btCachacaN.isSelected()) {
            valorRestaurante = 5;
            tipoRestaurante = "Cachaca Normal";
        } else if (btCachacaN.isSelected()) {
            valorRestaurante = 7;
            tipoRestaurante = "Cachaca com Mel";
        } else if (btCachacaM.isSelected()) {
            valorRestaurante = 5;
            tipoRestaurante = "Cachaca Normal";
        } else if (btJuizo.isSelected()) {
            valorRestaurante = 5;
            tipoRestaurante = "Juizo";
        } else if (btSerraLimpa.isSelected()) {
            valorRestaurante = 5;
            tipoRestaurante = "Serra Limpa";
        }

    }*/
    public boolean isSelectedRoom() {
        if (btTapioca.isSelected() || btBolo.isSelected()
                || btCanjica.isSelected() || btPamonha.isSelected()
                || btSelfService.isSelected() || btAgua.isSelected()
                || btCachacaN.isSelected() || btCachacaM.isSelected()
                || btJuizo.isSelected() || btSerraLimpa.isSelected()) {
            return true;
        }
        JOptionPane.showMessageDialog(null, "Selecione uma opção");
        return false;
    }

    public void exibeInformacoesCompra() {
        tfHospede.setText(String.valueOf(EscolherHospede.getSelectedItem()));
        Object[] dados = restauranteSelecionado();
        tfOpcao.setText(String.valueOf(dados[0]));

    }

    private Object[] restauranteSelecionado() {
        if (btTapioca.isSelected()) {
            return classRestaurante.listaRestaurante[0];
        } else if (btBolo.isSelected()) {
            return classRestaurante.listaRestaurante[1];
        } else if (btCanjica.isSelected()) {
            return classRestaurante.listaRestaurante[2];
        } else if (btPamonha.isSelected()) {
            return classRestaurante.listaRestaurante[3];
        } else if (btSelfService.isSelected()) {
            return classRestaurante.listaRestaurante[4];
        } else if (btAgua.isSelected()) {
            return classRestaurante.listaRestaurante[5];
        } else if (btCachacaN.isSelected()) {
            return classRestaurante.listaRestaurante[6];
        } else if (btCachacaM.isSelected()) {
            return classRestaurante.listaRestaurante[7];
        } else if (btJuizo.isSelected()) {
            return classRestaurante.listaRestaurante[8];
        } else {
            return classRestaurante.listaRestaurante[9];
        }

    }

    private Object[] pegaCampos() {
        int posicao = EscolherHospede.getSelectedIndex();
        Object[] campos = {
            this.tfPorcoes.getText().trim(),
            this.arrayListHospede.get(posicao),};
        return campos;
    }

    private void carregarTableRestaurante(String nome) {
        DefaultTableModel modelo = new DefaultTableModel(new Object[]{"ID", "Nome", "Consumido", "Data I.", "Data F."}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        if (!nome.equals("")) {
            for (int i = 0; i < this.arrayListHospede.size(); i++) {
                for (int j = 0; j < this.arrayListRestaurante.size(); j++) {

                    if (this.arrayListHospede.get(i).getNome().equals(nome)
                            && this.arrayListHospede.get(i).getCpf().equals(this.arrayListRestaurante.get(j).getHospede_id().getCpf())) {

                        modelo.addRow(new Object[]{
                            i,
                            this.arrayListHospede.get(i).getNome(),
                            this.arrayListRestaurante.get(j).getTipoEscolhido(), //errado só pra mostrar
                            this.arrayListHospede.get(i).getData_entrada(),
                            this.arrayListHospede.get(i).getData_saida(),});
                    }
                }
            }

        } else {
            for (int i = 0; i < this.arrayListHospede.size(); i++) {
                for (int j = 0; j < this.arrayListRestaurante.size(); j++) {

                    if (this.arrayListHospede.get(i).getCpf().equals(this.arrayListRestaurante.get(j).getHospede_id().getCpf())) {
                        modelo.addRow(new Object[]{
                            i,
                            this.arrayListHospede.get(i).getNome(),
                            this.arrayListRestaurante.get(j).getTipoEscolhido(), //errado só pra mostrar
                            this.arrayListHospede.get(i).getData_entrada(),
                            this.arrayListHospede.get(i).getData_saida(),});
                    }
                }
            }
        }

        TableRestaurante.setModel(modelo);
    }

    private classRestaurante instanceClass() {
        //int porcoes_unidades, String tipoEscolhido, int valorRestaurante, Hospede hospede_id
        Object[] dados = pegaCampos();
        Object[] dados1 = restauranteSelecionado();
        classRestaurante rest = new classRestaurante(
                Integer.valueOf(String.valueOf(dados[0])),
                String.valueOf(dados1[0]),
                Integer.valueOf(String.valueOf(dados1[1])),
                (Hospede) dados[1]
        );
        return rest;
    }

}
