/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Classes.Aluguel_Carros;
import Classes.classBabySitter;
import Classes.Hospede;
import Classes.Quartos;
import Classes.classRestaurante;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.text.BadLocationException;
import static view.Interno1.stringToDate;

/**
 *
 * @author Paulo
 */
public class Principal extends javax.swing.JFrame {

    ArrayList<Hospede> arrayListHospede;
    ArrayList<Quartos> arrayListQuartos;
    ArrayList<Aluguel_Carros> arrayListAluguel;
    ArrayList<classRestaurante> arrayListRestaurante;
    ArrayList<classBabySitter> arrayListBabySitter;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().getResource("/view/img/favicon4.png")).getImage());

        this.arrayListHospede = new ArrayList();
        this.arrayListQuartos = new ArrayList();
        this.arrayListAluguel = new ArrayList();
        this.arrayListRestaurante = new ArrayList();
        this.arrayListBabySitter = new ArrayList();

        criaRegistro();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        botaoHospede = new javax.swing.JLabel();
        botaoQuartos = new javax.swing.JLabel();
        botaoCarros = new javax.swing.JLabel();
        botaoRestaurante = new javax.swing.JLabel();
        botaoBaby = new javax.swing.JLabel();
        botaoPagar = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        botaoHospede.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botaoHospede.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/icone1.png"))); // NOI18N
        botaoHospede.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoHospede.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoHospedeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoHospedeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoHospedeMouseExited(evt);
            }
        });

        botaoQuartos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/icone2.png"))); // NOI18N
        botaoQuartos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoQuartos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoQuartosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoQuartosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoQuartosMouseExited(evt);
            }
        });

        botaoCarros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/icone3.png"))); // NOI18N
        botaoCarros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoCarros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoCarrosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoCarrosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoCarrosMouseExited(evt);
            }
        });

        botaoRestaurante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/icone4.png"))); // NOI18N
        botaoRestaurante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoRestaurante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoRestauranteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoRestauranteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoRestauranteMouseExited(evt);
            }
        });

        botaoBaby.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/icone5.png"))); // NOI18N
        botaoBaby.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoBaby.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoBabyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoBabyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoBabyMouseExited(evt);
            }
        });

        botaoPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/icone6.png"))); // NOI18N
        botaoPagar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoPagar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoPagarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoPagarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoPagarMouseExited(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(207, 207, 207));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1779, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 622, Short.MAX_VALUE)
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/gif.gif"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(360, 360, 360)
                                .addComponent(botaoCarros))
                            .addComponent(botaoHospede)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(220, 220, 220)
                                .addComponent(botaoQuartos))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(510, 510, 510)
                                .addComponent(botaoRestaurante)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaoBaby)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addComponent(botaoPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(49, 49, 49)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoCarros)
                    .addComponent(botaoHospede)
                    .addComponent(botaoQuartos)
                    .addComponent(botaoRestaurante)
                    .addComponent(botaoBaby)
                    .addComponent(botaoPagar)))
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1071, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 611, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoPagarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoPagarMouseExited
        botaoPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/icone6.png")));
    }//GEN-LAST:event_botaoPagarMouseExited

    private void botaoPagarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoPagarMouseEntered
        botaoPagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/icone6b.png")));
    }//GEN-LAST:event_botaoPagarMouseEntered

    private void botaoPagarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoPagarMouseClicked
        Interno6 i = null;
        try {
            i = new Interno6(this, true,this.arrayListQuartos,this.arrayListHospede,this.arrayListAluguel,
                    this.arrayListRestaurante,this.arrayListBabySitter);
        } catch (BadLocationException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        i.setVisible(true);
        
    }//GEN-LAST:event_botaoPagarMouseClicked

    private void botaoBabyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoBabyMouseExited
        botaoBaby.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/icone5.png")));
    }//GEN-LAST:event_botaoBabyMouseExited

    private void botaoBabyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoBabyMouseEntered
        botaoBaby.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/icone5b.png")));
    }//GEN-LAST:event_botaoBabyMouseEntered

    private void botaoBabyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoBabyMouseClicked
        Interno5 i = new Interno5(this, true, this.arrayListBabySitter, this.arrayListHospede);
        i.setVisible(true);
    }//GEN-LAST:event_botaoBabyMouseClicked

    private void botaoRestauranteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoRestauranteMouseExited
        botaoRestaurante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/icone4.png")));
    }//GEN-LAST:event_botaoRestauranteMouseExited

    private void botaoRestauranteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoRestauranteMouseEntered
        botaoRestaurante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/icone4b.png")));
    }//GEN-LAST:event_botaoRestauranteMouseEntered

    private void botaoRestauranteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoRestauranteMouseClicked
        Interno4 i = new Interno4(this, true, this.arrayListRestaurante, this.arrayListHospede);
        i.setVisible(true);
    }//GEN-LAST:event_botaoRestauranteMouseClicked

    private void botaoCarrosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoCarrosMouseExited
        botaoCarros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/icone3.png")));
    }//GEN-LAST:event_botaoCarrosMouseExited

    private void botaoCarrosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoCarrosMouseEntered
        botaoCarros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/icone3b.png")));
    }//GEN-LAST:event_botaoCarrosMouseEntered

    private void botaoCarrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoCarrosMouseClicked
        Interno3 i = new Interno3(this, true, this.arrayListAluguel, this.arrayListHospede);
        i.setVisible(true);
    }//GEN-LAST:event_botaoCarrosMouseClicked

    private void botaoQuartosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoQuartosMouseExited
        botaoQuartos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/icone2.png")));
    }//GEN-LAST:event_botaoQuartosMouseExited

    private void botaoQuartosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoQuartosMouseEntered
        botaoQuartos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/icone2b.png")));
    }//GEN-LAST:event_botaoQuartosMouseEntered

    private void botaoQuartosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoQuartosMouseClicked
        Interno2 i = new Interno2(this, true, this.arrayListQuartos, this.arrayListHospede);
        i.setVisible(true);
    }//GEN-LAST:event_botaoQuartosMouseClicked

    private void botaoHospedeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoHospedeMouseExited
        botaoHospede.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/icone1.png")));
    }//GEN-LAST:event_botaoHospedeMouseExited

    private void botaoHospedeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoHospedeMouseEntered
        botaoHospede.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/icone1b.png")));
    }//GEN-LAST:event_botaoHospedeMouseEntered

    private void botaoHospedeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoHospedeMouseClicked
        Interno1 i = new Interno1(this, true, this.arrayListHospede);
        i.setVisible(true);
    }//GEN-LAST:event_botaoHospedeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    private void criaRegistro() {

        //Hospede(String nome, String cpf, String telefone, int cartao_credito, Date data_entrada, Date data_saida)
        for (int i = 0; i < 30; i++) {
            Hospede h = new Hospede(
                    "Nome" + i,
                    "CPF" + i,
                    "Telefone" + i,
                    "123456789",
                    stringToDate("2018/07/06", "yyyy/MM/dd"),
                    stringToDate("2018/07/09", "yyyy/MM/dd"),
                    0
            );
            this.arrayListHospede.add(h);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel botaoBaby;
    private javax.swing.JLabel botaoCarros;
    private javax.swing.JLabel botaoHospede;
    private javax.swing.JLabel botaoPagar;
    private javax.swing.JLabel botaoQuartos;
    private javax.swing.JLabel botaoRestaurante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
